version: 3

dotenv: [.env]
env:
  APP_NAME: main
  TEMP_DIR: ./tmp
  BUILD_DIR: ./cmd/web
  MIGRATIONS_DIR: mysql/migrations

tasks:
  mysql-up: docker compose  -f  ./mysql/docker-compose.yaml up -d
  mysql-down: docker compose  -f  ./mysql/docker-compose.yaml down

  templ-generate:
    cmds:
      - templ generate
  build:
    deps: [templ-generate]
    cmds:
      - go build -o  $TEMP_DIR/$APP_NAME    $BUILD_DIR
  run:
    deps: [build]
    cmds:
      - ./$TEMP_DIR/$APP_NAME
  clean:
    cmds:
      - rm -rf $TEMP_DIR
  help:
    cmds:
      - ./$TEMP_DIR/$APP_NAME -h
  migrate-new:
    desc: task migrate -- [migration_pair_name]
    cmds:
      - migrate create -seq -ext=.sql -dir=$MIGRATIONS_DIR {{.CLI_ARGS}}
  migrate-up:
    desc: execute migrations
    cmds:
      - migrate -path=$MIGRATIONS_DIR -database=mysql://$SNIPPETBOX_MYSQL_DSN up
  migrate-down:
    desc: down all migrations
    cmds:
      - migrate -path=$MIGRATIONS_DIR -database=mysql://$SNIPPETBOX_MYSQL_DSN down
  migrate-goto:
    desc: migrate to a specific version
    cmds:
      - migrate -path=$MIGRATIONS_DIR -database=mysql://$SNIPPETBOX_MYSQL_DSN  goto {{.CLI_ARGS}}
  migrate-force:
    desc: used for fixing errors in SQL migrations
    cmds:
      - migrate -path=$MIGRATIONS_DIR -database=mysql://$SNIPPETBOX_MYSQL_DSN force {{.CLI_ARGS}}

  migrate-version:
    desc: show current version
    cmds:
      - migrate -path=$MIGRATIONS_DIR -database=$DB_DSN version
