version: 3



dotenv: [.env]
env:
  APP_NAME: main
  TEMP_DIR: ./tmp

tasks:
  build:
    cmds:
      - go build -o  $TEMP_DIR/$APP_NAME    .
  run:
    deps: [build]
    cmds:
      - ./$TEMP_DIR/$APP_NAME
  clean:
    cmds:
      - rm -rf $TEMP_DIR
