// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.501
package snippet

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"fmt"
	"time"
)

type ViewData struct {
	ID      string
	Title   string
	Content string
	Created string
	Expires string
}

func NewViewData(m *Model) ViewData {
	return ViewData{
		ID:      fmt.Sprint(m.ID),
		Title:   m.Title,
		Content: m.Content,
		Created: formatCreateTime(m.Created, "Africa/Cairo"),
		Expires: formatExpireTime(m.Expires, "Africa/Cairo"),
	}
}

func formatCreateTime(t time.Time, userTimeZone string) string {
	userLocation, err := time.LoadLocation(userTimeZone)
	if err != nil {
		// Handle the error, e.g., fall back to a default time zone.
		return "Error loading user's time zone"
	}

	t = t.In(userLocation)

	currentTime := time.Now().In(userLocation)
	diff := currentTime.Sub(t)

	layout := "2006-01-02 15:04"

	if diff.Seconds() < 60 {
		return "Just now"
	}

	if diff.Minutes() < 60 {
		return fmt.Sprintf("%.0f minutes ago", diff.Minutes())
	}

	if diff.Hours() < 24 {
		return fmt.Sprintf("%.0f hours ago", diff.Hours())
	}

	if diff.Hours() < 24*7 {
		return t.Format("Monday")
	}

	return t.Format(layout)
}

func formatExpireTime(t time.Time, userTimeZone string) string {
	userLocation, err := time.LoadLocation(userTimeZone)
	if err != nil {
		// Handle the error, e.g., fall back to a default time zone.
		return "Error loading user's time zone"
	}

	t = t.In(userLocation)

	currentTime := time.Now().In(userLocation)
	diff := t.Sub(currentTime)

	// Display seconds remaining
	if diff.Seconds() < 60 {
		return fmt.Sprintf("Expires in %.0f seconds", diff.Seconds())
	}

	// Display minutes remaining
	if diff.Minutes() < 60 {
		return fmt.Sprintf("Expires in %.0f minutes", diff.Minutes())
	}

	// Display hours remaining
	if diff.Hours() < 24 {
		return fmt.Sprintf("Expires in %.0f hours", diff.Hours())
	}

	// Display days remaining
	if diff.Hours() < 24*7 {
		return fmt.Sprintf("Expires in %.0f days", diff.Hours()/24)
	}

	// Display months remaining
	if diff.Hours() < 24*30 {
		return fmt.Sprintf("Expires in %.0f months", diff.Hours()/24/30)
	}

	// Display years remaining
	if diff.Hours() < 24*365 {
		return fmt.Sprintf("Expires in %.0f years", diff.Hours()/24/365)
	}

	// Display the date and time for expiration
	layout := "2006-01-02 15:04"
	return fmt.Sprintf("Expires on %s", t.Format(layout))
}

func ViewSnippet(data ViewData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"snippet\"><div class=\"bg-gray-700 p-6 rounded-lg shadow-md mb-4\"><div class=\"flex justify-end mb-2\"><button class=\"text-sm text-gray-500 mr-2 hover:text-red-500\" hx-confirm=\"Are you sure you want to delete this resource?\" hx-delete=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString("/snippets/" + data.ID))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-push-url=\"false\" hx-target=\"closest .snippet\" hx-swap=\"outerHTML swap:1s scroll:bottom\" transition:true>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `Delete`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button> <button class=\"text-sm text-gray-500 hover:text-blue-500\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := `Update`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button></div><div class=\"text-sm text-gray-500 mb-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := `Published: `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(data.Created)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `snippet/view.templ`, Line: 125, Col: 29}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var6 := `| Expires: `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(data.Expires)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `snippet/view.templ`, Line: 125, Col: 57}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><h2 class=\"text-xl font-semibold mb-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(data.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `snippet/view.templ`, Line: 127, Col: 54}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h2><p class=\"text-gray-300\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(data.Content)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `snippet/view.templ`, Line: 128, Col: 42}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var10 := ` Hidden input field for snippet ID `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var10)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><input type=\"hidden\" name=\"snippet_id\" value=\"{ data.ID }\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
